# Generated by Django 5.0.6 on 2024-06-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0004_category_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactDealer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("city", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=15)),
                ("date", models.DateField()),
            ],
        ),
    ]
