# Generated by Django 5.0.6 on 2024-06-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactdealer",
            name="item_name",
            field=models.CharField(default="Truck", max_length=255),
        ),
    ]
